# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  vlmnetwork:

services:

  ca_dealer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-dealer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.dealer.vlm.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/priv_sk

    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server/ca.dealer.vlm.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server/priv_sk -b admin:adminpw -d'
    volumes:
      # - ../organizations/fabric-ca/dealer:/etc/hyperledger/fabric-ca-server
      - ../crypto-config/peerOrganizations/dealer.vlm.com/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_dealer
    networks:
      - vlmnetwork

  ca_rta:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-rta
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.rta.vlm.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/priv_sk
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start  --ca.certfile /etc/hyperledger/fabric-ca-server/ca.rta.vlm.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server/priv_sk -b admin:adminpw -d'
    volumes:
      # - ../organizations/fabric-ca/rta:/etc/hyperledger/fabric-ca-server
      - ../crypto-config/peerOrganizations/rta.vlm.com/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_rta
    networks:
      - vlmnetwork

  # ca_orderer:
  #   image: hyperledger/fabric-ca:$IMAGE_TAG
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca-orderer
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_PORT=9054
  #     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.vlm.com-cert.pem
  #     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/priv_sk
  #   ports:
  #     - "9054:9054"
  #   command: sh -c 'fabric-ca-server start  --ca.certfile /etc/hyperledger/fabric-ca-server/ca.vlm.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server/priv_sk -b admin:adminpw -d'
  #   volumes:
  #     # - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
  #     - ../crypto-config/ordererOrganizations/ge.com/ca:/etc/hyperledger/fabric-ca-server
  #   container_name: ca_orderer
  #   networks:
  #     - vlmnetwork
