# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  vlmnetwork:

services:
  couchdbdealer:
    container_name: couchdbdealer
    image: couchdb:3.1.1
    
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    ports:
      - "5984:5984"
    networks:
      - vlmnetwork

  peer0.dealer.vlm.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbdealer:5984

      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdbdealer

  couchdbrta:
    container_name: couchdbrta
    image: couchdb:3.1.1

    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw

    ports:
      - "7984:5984"
    networks:
      - vlmnetwork

  peer0.rta.vlm.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbrta:5984

      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdbrta
